// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package Player

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func PlayerContract() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"w-full h-fit rounded-3xl shadow-xl p-5 bg-primary\"><div class=\"w-auto\"><div class=\"text-2xl font-bold\">Contract</div><div class=\"mt-3 h-full flex-col items-start\"><div class=\"flex flex-row h-full justify-between mt-4\"><div class=\"text-sm font-semibold\">Wage: </div><div class=\"text-sm\">A lot</div></div><div class=\"flex flex-row h-full justify-between mt-4\"><div class=\"text-sm font-semibold\">Current Club: </div><div class=\"text-sm\">Sporting CP</div></div><div class=\"flex flex-row h-full justify-between mt-4\"><div class=\"text-sm font-semibold\">Value: </div><div class=\"text-sm\">100M€</div></div><div class=\"flex flex-row h-full justify-between mt-4\"><div class=\"text-sm font-semibold\">Contract Duration: </div><div class=\"text-sm\">3 year</div></div><div class=\"flex flex-row h-full justify-between mt-4\"><div class=\"text-sm font-semibold\">Contract End: </div><div class=\"text-sm\">Too soon</div></div><div class=\"flex flex-row h-full justify-between mt-4\"><div class=\"text-sm font-semibold\">Release Clause: </div><div class=\"text-sm\">100M€</div></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
