// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package Player

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func PlayerBio() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"w-full h-fit rounded-3xl shadow-xl p-4 bg-primary\"><div class=\"w-auto flex flex-row justify-between\"><div class=\"max-w-40 h-56\"><img class=\"h-full rounded-lg drop-shadow-lg object-cover\" src=\"https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fleonino.pt%2Fwp-content%2Fuploads%2F2023%2F08%2Fgyokeres.jpg&amp;f=1&amp;nofb=1&amp;ipt=bd6c969ebe7e0b59aad945ecdb24b1ec4af5997c5a3fa36bbc7d5e79f01305a1&amp;ipo=images\" alt=\"Player Image\"></div><div class=\" mt-3 h-full\"><div class=\"text-2xl font-bold\">Viktor Gyokeres</div><div class=\"flex flex-col h-full justify-around mt-4\"><div class=\"text-sm font-semibold\">Nationality: <span class=\"ml-auto font-normal\">Sweeden</span></div><div class=\"text-sm font-semibold\">Age: <span class=\"font-normal\">26</span></div><div class=\"text-sm font-semibold\">Height: <span class=\"font-normal\">180cm</span></div><div class=\"text-sm font-semibold\">Weight: <span class=\"font-normal\">85kg</span></div><div class=\"text-sm font-semibold\">Best Foot: <span class=\"font-normal\">Right</span></div></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
