version: "3.8"

services:
  go-app:
    build: .
    volumes:
      - .:/app
      - go-build:/go/pkg/mod
      - go-build:/root/.cache/go-build
      - /app/node_modules

    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - GO_ENV=development
      - NODE_ENV=development
    command: "/go/bin/air"
    networks:
      - app-network

volumes:
  go-build:

networks:
  app-network:
    driver: bridge
